### ISSUE TITLE
Update password reset migration

### ISSUE THREAD

**Issue by cacpmw** [global-devteam/laravel-api-password-reset#10]
Every laravel project comes with a password_resets migration. This migration file doesnt contain id nor timestamps.

Create a package migration to update that table in order to make it have both id and timestamps.

**Comment by beauraines** [comment]
I've not looked closely at the `password_resets` table, so I'm asking from a place of ignorance - why does it need these fields for the API reset?

**Comment by cacpmw** [comment]
> I've not looked closely at the `password_resets` table, so I'm asking from a place of ignorance - why does it need these fields for the API reset?

@beauraines I need `id` for the formrequest validation rules and the `updated_at` to check if token is expired.
