### ISSUE TITLE
Enable package auto discovery

### ISSUE THREAD

**Issue by beauraines** [global-devteam/laravel-api-password-reset#20]

**Comment by beauraines** [comment]
Seems like this is the `extra` property in composer.json

```
"extra": {
        "laravel": {
            "providers": [
                "Tkeer\\Mailbase\\MailbaseServiceProvider"
            ]
        }
    }
```

**Comment by cacpmw** [comment]
@beauraines why is this not on closed? It does have the closed tag on it. 
Shouldnt this have been moved automatically?

**Comment by cacpmw** [comment]
@beauraines nevermind. It just moved itself to closed LOL
